name: CI/CD Pipeline

run-name: "${{github.repository}} #${{github.run_number}} - Building ${{github.ref_name}} by @${{github.actor}}"

on:
  workflow_dispatch:  
  push:
    branches: [ "develop" ]

env:
  ORG: ${{github.repository_owner}}

jobs:
  dump:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Dump 
        run: |
            echo "ORG = ${{ env.ORG }}"
            echo "ORGVAR1 = ${{ vars.ORGVAR1 }}"
            echo "ORGSEC1 = ${{ secrets.ORGSEC1 }}"
            echo "unknown secret is ${{ secrets.DOES_NOT_EXIST }}"
            echo "ENVVAR1 = ${{ vars.ENVVAR1 }}"
            echo "ENVSEC1 = ${{ secrets.ENVSEC1 }}"

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          #token: ${{ secrets.PAT }}
          repository: ${{ env.ORG }}/gs-dso-templates
          event-type: my-event
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

  
  #ci:
  #  uses: magrni/gs-dso-actions/.github/workflows/dotnet-ci.yml@main
  #  needs: dump
    #with:
    #  custom_param: "Some literal string 21"
