name: Test Pipeline

run-name: "#${{github.run_number}} - Testing ${{github.ref_name}} by @${{github.actor}}"

on:
  workflow_dispatch:  

env:
  stack: 'net/20'
  credentials: "{ \"tenantId\": \"tenantid\", \"clientId\": \"clientId\", \"clientSecret\": \"clientSecret\" }"

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Set spec path
        run: |
          echo "apim_credential=${{ env.credentials }}" >> $GITHUB_ENV
          if [[ ${{ env.stack }} = "node"* ]]; then
            echo "spec_path=repo/swagger-json" >> $GITHUB_ENV
          elif [[ ${{ env.stack }} = "net"* ]]; then
            echo "spec_path=repo/swagger/swagger.json" >> $GITHUB_ENV
          else
            echo "stack no valido"
            exit 1
          fi        

      - run: echo "${{ env.spec_path }}"

      - name: Update Azure API Management OpenAPI schema
        uses: OssiPesonen/action-update-api-management-openapi@master
        with:
          openAPIDefinitions: https://dev-cloud.svc.galiciaseguros.com.ar/gs-dso-gitflow-bff/swagger-json
          apiId: /subscriptions/b80ae9bd-4aa9-4f1e-ae01-6a08372e16e9/resourceGroups/rg-dev-apim-eastus/providers/Microsoft.ApiManagement/service/apim-dev-gs/apis/gs-dso-gitflow-bff_id
          apiUrlSuffix: gs-dso-gitflow-bff
          credentials: "${{ env.apim_credential }}"
